# permissions for end users to edit backupkubeadmins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupkubeadmin-editor-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - backupkubeadmins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - backupkubeadmins/status
  verbs:
  - get
