# permissions for end users to edit clusterupgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterupgrade-editor-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - clusterupgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - clusterupgrades/status
  verbs:
  - get
