# permissions for end users to edit day2ops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: day2op-editor-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - day2ops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - day2ops/status
  verbs:
  - get
