# permissions for end users to view day2ops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: day2op-viewer-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - day2ops
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - day2ops/status
  verbs:
  - get
