# permissions for end users to view defaultprojectrequesttemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: defaultprojectrequesttemplate-viewer-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - defaultprojectrequesttemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - defaultprojectrequesttemplates/status
  verbs:
  - get
