# permissions for end users to edit defaultprojectrequesttemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: defaultprojectrequesttemplate-editor-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - defaultprojectrequesttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - defaultprojectrequesttemplates/status
  verbs:
  - get
