# permissions for end users to edit defaultnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: defaultnamespaces-editor-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - defaultnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - defaultnamespaces/status
  verbs:
  - get
