# permissions for end users to edit defaultstorageclassselects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: defaultstorageclassselect-editor-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - defaultstorageclassselects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - defaultstorageclassselects/status
  verbs:
  - get
