# permissions for end users to view defaultstorageclassselects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: defaultstorageclassselect-viewer-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - defaultstorageclassselects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - defaultstorageclassselects/status
  verbs:
  - get
