# permissions for end users to edit etcddefrags.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcddefrag-editor-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - etcddefrags
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - etcddefrags/status
  verbs:
  - get
