# permissions for end users to edit etcdbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdbackup-editor-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - etcdbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - etcdbackups/status
  verbs:
  - get
