# permissions for end users to edit etcdencrypts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdencrypt-editor-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - etcdencrypts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - etcdencrypts/status
  verbs:
  - get
