# permissions for end users to edit expandnodeportranges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: expandnodeportrange-editor-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - expandnodeportranges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - expandnodeportranges/status
  verbs:
  - get
