# permissions for end users to edit privateclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privatecluster-editor-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - privateclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - privateclusters/status
  verbs:
  - get
