# permissions for end users to edit pruneobjects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pruneobjects-editor-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - pruneobjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - pruneobjects/status
  verbs:
  - get
