# permissions for end users to view restorekubeadmins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restorekubeadmin-viewer-role
rules:
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - restorekubeadmins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - day2ops.redhatcop.redhat.io
  resources:
  - restorekubeadmins/status
  verbs:
  - get
